# Base configs
baseurl: "https://george-taschina.github.io/photography/
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by George Taschina"
subtitle: "See the world through my eyes!"
author: "George Taschina"
header:
 title: "Photography"
 subtitle: "by George Taschina
footer:
 name: "Hey there, my name is George"
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: "
  dribbble: ""
  linkedin: ""
  github: ""
